# -*- coding: utf-8 -*-
"""day-14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0oN0gpxlQK3WzJIjZnhxaERx4YPtZGP
"""

import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=sns.load_dataset('iris')
df

df.duplicated()

df.duplicated().sum()

df['species'].unique()

setosa 1
versi 2
virginioca 3

df['species'].replace({'setosa':1,'versicolor':2,'virginica':3},inplace=True)

df.info()

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb.fit_transform(df['species'])

df

df['species'].unique()

oh_species=pd.get_dummies(df['species'])
df=pd.concat([df.drop('species',axis=1),oh_species],axis=1)

df

